### ISSUE TITLE
ActiveJob undefined method 'async'

### ISSUE THREAD

**Issue by willyko** [RailsApps/rails-mailinglist-activejob#5]
I was able to start the server but upon entering email on the page, I received the error below

```
NoMethodError - undefined method `async' for #<ActiveJob::QueueAdapters::SuckerPunchAdapter::JobWrapper:0x000001066cb568>:
  activejob (4.2.5.2) lib/active_job/queue_adapters/sucker_punch_adapter.rb:23:in `enqueue'
  activejob (4.2.5.2) lib/active_job/enqueuing.rb:71:in `block in enqueue'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:117:in `call'
```

Any idea?

**Comment by willyko** [comment]
oh never mind! found the answer 
https://github.com/brandonhilkert/sucker_punch#active-job
